apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 120m0s
  url: https://github.com/kyverno/kyverno
  ignore: |
    /*
    !/config/
  ref:
    tag: "v1.7.2-rc1"
