apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-core
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: tekton-core
  serviceAccountName: kustomize-controller
  path: ./infrastructure/tekton
  prune: true
  wait: true
  timeout: 10m